vich_uploader:
    db_driver: orm

    mappings:

        images:
            uri_prefix: /images/site
            upload_destination: '%kernel.project_dir%/public/images/site'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        candidatures:
            uri_prefix: /candidatures/justificatifs
            upload_destination: '%kernel.project_dir%/public/candidatures/justificatifs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
