<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260313132218 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agenda_acceuil CHANGE titre_black titre_black VARCHAR(255) DEFAULT NULL, CHANGE titre_gris titre_gris VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE banniere_award CHANGE badge badge VARCHAR(255) DEFAULT NULL, CHANGE titre_blanc titre_blanc VARCHAR(255) DEFAULT NULL, CHANGE titre_rouge titre_rouge VARCHAR(255) DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_path image_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE banniere_billeterie CHANGE badge badge VARCHAR(255) DEFAULT NULL, CHANGE titre_blanc titre_blanc VARCHAR(255) DEFAULT NULL, CHANGE titre_rouge titre_rouge VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE banniere_contact CHANGE titre titre VARCHAR(255) DEFAULT NULL, CHANGE infoline infoline VARCHAR(255) DEFAULT NULL, CHANGE description_infoline description_infoline VARCHAR(255) DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE description_email description_email VARCHAR(255) DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_path image_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE banniere_exposant CHANGE badge badge VARCHAR(255) DEFAULT NULL, CHANGE titre_blanc titre_blanc VARCHAR(255) DEFAULT NULL, CHANGE titre_or titre_or VARCHAR(255) DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_path image_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE banniere_galerie CHANGE badge badge VARCHAR(255) DEFAULT NULL, CHANGE titre_blanc titre_blanc VARCHAR(255) DEFAULT NULL, CHANGE titre_rouge titre_rouge VARCHAR(255) DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_path image_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE banniere_sponsor CHANGE badge badge VARCHAR(255) DEFAULT NULL, CHANGE titre_blanc titre_blanc VARCHAR(255) DEFAULT NULL, CHANGE titre_or titre_or VARCHAR(255) DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_path image_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE candidature CHANGE nom_entreprise nom_entreprise VARCHAR(255) NOT NULL, CHANGE statut_entreprise statut_entreprise VARCHAR(255) NOT NULL, CHANGE num_rccm num_rccm VARCHAR(255) NOT NULL, CHANGE num_cc num_cc VARCHAR(255) NOT NULL, CHANGE adresse_siege adresse_siege VARCHAR(255) NOT NULL, CHANGE ville ville VARCHAR(255) NOT NULL, CHANGE pays pays VARCHAR(255) NOT NULL, CHANGE telephone telephone VARCHAR(255) NOT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE site_web site_web VARCHAR(255) DEFAULT NULL, CHANGE fullname_representant fullname_representant VARCHAR(255) NOT NULL, CHANGE fonction_representant fonction_representant VARCHAR(255) NOT NULL, CHANGE genre_representant genre_representant VARCHAR(255) NOT NULL, CHANGE pays_representant pays_representant VARCHAR(255) NOT NULL, CHANGE secteur_activite secteur_activite VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE carousel_acceuil CHANGE mini_titre mini_titre VARCHAR(255) DEFAULT NULL, CHANGE blanc blanc VARCHAR(255) DEFAULT NULL, CHANGE titre_or titre_or VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE file_name file_name VARCHAR(255) DEFAULT NULL, CHANGE file_path file_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE carousel_gala CHANGE badge badge VARCHAR(255) DEFAULT NULL, CHANGE titre titre VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE impact impact VARCHAR(255) DEFAULT NULL, CHANGE label_annee label_annee VARCHAR(255) DEFAULT NULL, CHANGE file_name file_name VARCHAR(255) DEFAULT NULL, CHANGE file_path file_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE carte_programme_acceuil CHANGE titre titre VARCHAR(255) DEFAULT NULL, CHANGE sous_titre sous_titre VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE svg svg VARCHAR(255) DEFAULT NULL, CHANGE file_name file_name VARCHAR(255) DEFAULT NULL, CHANGE file_path file_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE categorie_candidature CHANGE code code VARCHAR(255) NOT NULL, CHANGE label label VARCHAR(255) NOT NULL, CHANGE mini_titre mini_titre VARCHAR(255) DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_path image_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE categorie_dossier CHANGE code code VARCHAR(255) NOT NULL, CHANGE label label VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE cliche_galerie CHANGE legende legende VARCHAR(255) DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_path image_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE critere_award CHANGE label label VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE detail_agenda_acceuil CHANGE badge badge VARCHAR(255) DEFAULT NULL, CHANGE titre titre VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE lieu lieu VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE detail_galerie CHANGE edition edition VARCHAR(255) DEFAULT NULL, CHANGE titre titre VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE detail_opportunite_exposant CHANGE badge badge VARCHAR(255) DEFAULT NULL, CHANGE titre titre VARCHAR(255) DEFAULT NULL, CHANGE link_detail link_detail VARCHAR(255) DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_path image_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE detail_partenaire_acceuil CHANGE label_entreprise label_entreprise VARCHAR(255) DEFAULT NULL, CHANGE file_name file_name VARCHAR(255) DEFAULT NULL, CHANGE file_path file_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE dossier CHANGE nom_entreprise nom_entreprise VARCHAR(255) NOT NULL, CHANGE statut_entreprise statut_entreprise VARCHAR(255) NOT NULL, CHANGE num_rccm num_rccm VARCHAR(255) NOT NULL, CHANGE num_cc num_cc VARCHAR(255) NOT NULL, CHANGE ville_pays ville_pays VARCHAR(255) NOT NULL, CHANGE siteweb siteweb VARCHAR(255) DEFAULT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE telephone telephone VARCHAR(255) NOT NULL, CHANGE nom_rep nom_rep VARCHAR(255) NOT NULL, CHANGE fonction_rep fonction_rep VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE entreprise_hall_of_fame CHANGE raison_social raison_social VARCHAR(255) DEFAULT NULL, CHANGE facebook facebook VARCHAR(255) DEFAULT NULL, CHANGE linkedin linkedin VARCHAR(255) DEFAULT NULL, CHANGE site_web site_web VARCHAR(255) DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_path image_path VARCHAR(255) DEFAULT NULL, CHANGE badge badge VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE epicentre_acceuil CHANGE titre_black titre_black VARCHAR(255) DEFAULT NULL, CHANGE titre_gris titre_gris VARCHAR(255) DEFAULT NULL, CHANGE adresse_longue adresse_longue VARCHAR(255) DEFAULT NULL, CHANGE lien_carte lien_carte VARCHAR(255) DEFAULT NULL, CHANGE description_infoline description_infoline VARCHAR(255) DEFAULT NULL, CHANGE telephone telephone VARCHAR(255) DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE exposant CHANGE fullname fullname VARCHAR(255) NOT NULL, CHANGE entreprise entreprise VARCHAR(255) NOT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE type_prod type_prod VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE hall_of_fame_gala CHANGE badge badge VARCHAR(255) DEFAULT NULL, CHANGE titre_black titre_black VARCHAR(255) DEFAULT NULL, CHANGE titre_rouge titre_rouge VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agenda_acceuil CHANGE titre_black titre_black VARCHAR(1000) DEFAULT NULL, CHANGE titre_gris titre_gris VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE banniere_award CHANGE badge badge VARCHAR(1000) DEFAULT NULL, CHANGE titre_blanc titre_blanc VARCHAR(1000) DEFAULT NULL, CHANGE titre_rouge titre_rouge VARCHAR(1000) DEFAULT NULL, CHANGE image_name image_name VARCHAR(1000) DEFAULT NULL, CHANGE image_path image_path VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE banniere_billeterie CHANGE badge badge VARCHAR(1000) DEFAULT NULL, CHANGE titre_blanc titre_blanc VARCHAR(1000) DEFAULT NULL, CHANGE titre_rouge titre_rouge VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE banniere_contact CHANGE titre titre VARCHAR(1000) DEFAULT NULL, CHANGE infoline infoline VARCHAR(1000) DEFAULT NULL, CHANGE description_infoline description_infoline VARCHAR(1000) DEFAULT NULL, CHANGE email email VARCHAR(1000) DEFAULT NULL, CHANGE description_email description_email VARCHAR(1000) DEFAULT NULL, CHANGE image_name image_name VARCHAR(1000) DEFAULT NULL, CHANGE image_path image_path VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE banniere_exposant CHANGE badge badge VARCHAR(1000) DEFAULT NULL, CHANGE titre_blanc titre_blanc VARCHAR(1000) DEFAULT NULL, CHANGE titre_or titre_or VARCHAR(1000) DEFAULT NULL, CHANGE image_name image_name VARCHAR(1000) DEFAULT NULL, CHANGE image_path image_path VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE banniere_galerie CHANGE badge badge VARCHAR(1000) DEFAULT NULL, CHANGE titre_blanc titre_blanc VARCHAR(1000) DEFAULT NULL, CHANGE titre_rouge titre_rouge VARCHAR(1000) DEFAULT NULL, CHANGE image_name image_name VARCHAR(1000) DEFAULT NULL, CHANGE image_path image_path VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE banniere_sponsor CHANGE badge badge VARCHAR(1000) DEFAULT NULL, CHANGE titre_blanc titre_blanc VARCHAR(1000) DEFAULT NULL, CHANGE titre_or titre_or VARCHAR(1000) DEFAULT NULL, CHANGE image_name image_name VARCHAR(1000) DEFAULT NULL, CHANGE image_path image_path VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE candidature CHANGE nom_entreprise nom_entreprise VARCHAR(1000) NOT NULL, CHANGE statut_entreprise statut_entreprise VARCHAR(1000) NOT NULL, CHANGE num_rccm num_rccm VARCHAR(1000) NOT NULL, CHANGE num_cc num_cc VARCHAR(1000) NOT NULL, CHANGE adresse_siege adresse_siege VARCHAR(1000) NOT NULL, CHANGE ville ville VARCHAR(1000) NOT NULL, CHANGE pays pays VARCHAR(1000) NOT NULL, CHANGE telephone telephone VARCHAR(1000) NOT NULL, CHANGE email email VARCHAR(1000) NOT NULL, CHANGE site_web site_web VARCHAR(1000) DEFAULT NULL, CHANGE fullname_representant fullname_representant VARCHAR(1000) NOT NULL, CHANGE fonction_representant fonction_representant VARCHAR(1000) NOT NULL, CHANGE genre_representant genre_representant VARCHAR(1000) NOT NULL, CHANGE pays_representant pays_representant VARCHAR(1000) NOT NULL, CHANGE secteur_activite secteur_activite VARCHAR(1000) NOT NULL');
        $this->addSql('ALTER TABLE carousel_acceuil CHANGE mini_titre mini_titre VARCHAR(1000) DEFAULT NULL, CHANGE blanc blanc VARCHAR(1000) DEFAULT NULL, CHANGE titre_or titre_or VARCHAR(1000) DEFAULT NULL, CHANGE description description VARCHAR(1000) DEFAULT NULL, CHANGE file_name file_name VARCHAR(1000) DEFAULT NULL, CHANGE file_path file_path VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE carousel_gala CHANGE badge badge VARCHAR(1000) DEFAULT NULL, CHANGE titre titre VARCHAR(1000) DEFAULT NULL, CHANGE description description VARCHAR(1000) DEFAULT NULL, CHANGE impact impact VARCHAR(1000) DEFAULT NULL, CHANGE label_annee label_annee VARCHAR(1000) DEFAULT NULL, CHANGE file_name file_name VARCHAR(1000) DEFAULT NULL, CHANGE file_path file_path VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE carte_programme_acceuil CHANGE titre titre VARCHAR(1000) DEFAULT NULL, CHANGE sous_titre sous_titre VARCHAR(1000) DEFAULT NULL, CHANGE description description VARCHAR(1000) DEFAULT NULL, CHANGE svg svg VARCHAR(1000) DEFAULT NULL, CHANGE file_name file_name VARCHAR(1000) DEFAULT NULL, CHANGE file_path file_path VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE categorie_candidature CHANGE code code VARCHAR(1000) NOT NULL, CHANGE label label VARCHAR(1000) NOT NULL, CHANGE mini_titre mini_titre VARCHAR(1000) DEFAULT NULL, CHANGE image_name image_name VARCHAR(1000) DEFAULT NULL, CHANGE image_path image_path VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE categorie_dossier CHANGE code code VARCHAR(1000) NOT NULL, CHANGE label label VARCHAR(1000) NOT NULL');
        $this->addSql('ALTER TABLE cliche_galerie CHANGE legende legende VARCHAR(1000) DEFAULT NULL, CHANGE image_name image_name VARCHAR(1000) DEFAULT NULL, CHANGE image_path image_path VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE critere_award CHANGE label label VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE detail_agenda_acceuil CHANGE badge badge VARCHAR(1000) DEFAULT NULL, CHANGE titre titre VARCHAR(1000) DEFAULT NULL, CHANGE description description VARCHAR(1000) DEFAULT NULL, CHANGE lieu lieu VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE detail_galerie CHANGE edition edition VARCHAR(1000) DEFAULT NULL, CHANGE titre titre VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE detail_opportunite_exposant CHANGE badge badge VARCHAR(1000) DEFAULT NULL, CHANGE titre titre VARCHAR(1000) DEFAULT NULL, CHANGE link_detail link_detail VARCHAR(1000) DEFAULT NULL, CHANGE image_name image_name VARCHAR(1000) DEFAULT NULL, CHANGE image_path image_path VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE detail_partenaire_acceuil CHANGE label_entreprise label_entreprise VARCHAR(1000) DEFAULT NULL, CHANGE file_name file_name VARCHAR(1000) DEFAULT NULL, CHANGE file_path file_path VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE dossier CHANGE nom_entreprise nom_entreprise VARCHAR(1000) NOT NULL, CHANGE statut_entreprise statut_entreprise VARCHAR(1000) NOT NULL, CHANGE num_rccm num_rccm VARCHAR(1000) NOT NULL, CHANGE num_cc num_cc VARCHAR(1000) NOT NULL, CHANGE ville_pays ville_pays VARCHAR(1000) NOT NULL, CHANGE siteweb siteweb VARCHAR(1000) DEFAULT NULL, CHANGE email email VARCHAR(1000) NOT NULL, CHANGE telephone telephone VARCHAR(1000) NOT NULL, CHANGE nom_rep nom_rep VARCHAR(1000) NOT NULL, CHANGE fonction_rep fonction_rep VARCHAR(1000) NOT NULL');
        $this->addSql('ALTER TABLE entreprise_hall_of_fame CHANGE raison_social raison_social VARCHAR(1000) DEFAULT NULL, CHANGE facebook facebook VARCHAR(1000) DEFAULT NULL, CHANGE linkedin linkedin VARCHAR(1000) DEFAULT NULL, CHANGE site_web site_web VARCHAR(1000) DEFAULT NULL, CHANGE image_name image_name VARCHAR(1000) DEFAULT NULL, CHANGE image_path image_path VARCHAR(1000) DEFAULT NULL, CHANGE badge badge VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE epicentre_acceuil CHANGE titre_black titre_black VARCHAR(1000) DEFAULT NULL, CHANGE titre_gris titre_gris VARCHAR(1000) DEFAULT NULL, CHANGE adresse_longue adresse_longue VARCHAR(1000) DEFAULT NULL, CHANGE lien_carte lien_carte VARCHAR(1000) DEFAULT NULL, CHANGE description_infoline description_infoline VARCHAR(1000) DEFAULT NULL, CHANGE telephone telephone VARCHAR(1000) DEFAULT NULL, CHANGE email email VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE exposant CHANGE fullname fullname VARCHAR(1000) NOT NULL, CHANGE entreprise entreprise VARCHAR(1000) NOT NULL, CHANGE email email VARCHAR(1000) NOT NULL, CHANGE type_prod type_prod VARCHAR(1000) NOT NULL');
        $this->addSql('ALTER TABLE hall_of_fame_gala CHANGE badge badge VARCHAR(1000) DEFAULT NULL, CHANGE titre_black titre_black VARCHAR(1000) DEFAULT NULL, CHANGE titre_rouge titre_rouge VARCHAR(1000) DEFAULT NULL, CHANGE description description VARCHAR(1000) DEFAULT NULL');
    }
}
